### PR TITLE
Fix pragma in FlashLoanSimpleReceiverBase.sol

### PR DESCRIPTION
**Pull request by WardenJakx**
Typo in pragma only allowing version 0.8.10

### CODE REVIEW

**Comment by Eloelo420thc** [comment]
Yes man

**Comment by silvercondor** [comment]
yes please resolve

**Comment by miguelmtzinf** [comment]
Hey @WardenJakx thanks for the contribution!
Could you do the same for `FlashLoanSimpleReceiverBase.sol` please?

**Comment by miguelmtzinf** [comment]
Closing this in favor of #861 
Thanks @WardenJakx

**Pull request closed without merging**
