### PR TITLE
Soften solidity version of Datatypes libraries

### LINKED ISSUE #738: Change DataTypes.sol solidity version to ^0.8.0 to support all 0.8.x
Currently, the DataTypes.sol file is using `pragma solidity 0.8.10;` whereas all other files like `IPool.sol` are using `^0.8.0`.
When trying to compile contracts using ^0.8.15, I get the following error: 

image

Would it be possible to change the solidity version for this too, to support other versions?

File found in: `@aave/core-v3/contracts/protocol/libraries/types/DataTypes.sol`

### PR DESCRIPTION
**Pull request by miguelmtzinf**
Close #738

### CODE REVIEW

**Comment by miguelmtzinf** [comment]
It would be great to count with @eboadom and @kyzia551 feedback on this. I wonder if we should also soften the version of other libraries like:
- helpers/*
- math/*

**Review by eboadom — APPROVED** [review]

**Comment by kyzia551** [comment]
> It would be great to count with @eboadom and @kyzia551 feedback on this. I wonder if we should also soften the version of other libraries like:
> 
> * helpers/*
> * math/*

You know my opinion, that we should make it soft everywhere, and you know that auditors do not agree with it :')

**Comment by sakulstra** [comment]
For everything that might potentially be used by a 3th party fixed version is annoying.

**Comment by miguelmtzinf** [comment]
Thanks @kyzia551 @eboadom  @sakulstra , I think we found a good balance!

**Pull request merged**
